/** What the fortune cookie on the homepage can say. One is picked at random per crack. */
export const fortunes = [
  "Your future is in superposition. Stop measuring it.",
  "A great opportunity is entangled with you. Distance is no excuse.",
  "You will tunnel through a barrier you thought was solid.",
  "Decoherence is temporary. Your curiosity is not.",
  "Someone nearby shares your wavefunction. Say hello at the next meetup.",
  "Today you will collapse into the best version of yourself.",
  "Error correction begins with admitting you have errors.",
  "You cannot clone this fortune. Read it carefully.",
  "Shor will factor your problems. Be patient.",
  "What you seek is closer than you think. About √N steps closer.",
  "Heisenberg was here. Or he was moving fast. Hard to say.",
  "A cat in a box is thinking about you. Possibly.",
  "Your next circuit will run on real hardware. Probably on the second try.",
  "Uncertainty is just possibility with better branding.",
  "Spin up. Things are looking up.",
  "Observe less, wonder more.",
  "You are one Hadamard away from a fresh perspective.",
  "Your coherence time is longer than you think.",
  "The collaborator you need is someone you haven't met yet.",
  "Measure twice, collapse once.",
  "Every expert was once in the |0⟩ state.",
  "You will soon find yourself in a mixed state. Embrace it.",
  "Somewhere a dilution fridge is at 10 millikelvin, and so is your chill.",
  "Interference can be constructive. Ask your question out loud.",
  "Your lucky gate is CNOT. Take control.",
  "In another branch of the multiverse, you already joined the Discord.",
  "Linear algebra will love you back. Eventually.",
  "The best time to learn quantum was 1925. The second best time is now.",
  "A bra and a ket walk into a bar. You'll get it after the next workshop.",
  "Your noise will average out. Keep sampling.",
];
