import type { FlagCode } from "@/lib/site";

export type NewsKind = "Community" | "On the road" | "Launch";

export type NewsItem = {
  date: string;
  displayDate: string;
  title: string;
  summary: string;
  image: string;
  url: string;
  country: FlagCode | null;
  kind: NewsKind;
};

/** Newest first. */
export const news: NewsItem[] = [
  {
    date: "2026-08-04",
    displayDate: "Aug 4, 2026",
    title: "QuantumX selected as a Qiskit Fall Fest 2026 host",
    summary: "We've been selected as an official host for IBM's Qiskit Fall Fest 2026.",
    image: "/images/news/qiskit-fall-fest-2026.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_were-super-excited-to-announce-that-quantumx-activity-7490337968432414720-vhCV",
    country: "in",
    kind: "Community",
  },
  {
    date: "2026-07-13",
    displayDate: "Jul 13, 2026",
    title: "Meet DsynQ, our new AI-assisted quantum photonic circuit design platform",
    summary: "DsynQ turns circuit requirements into fabrication-ready chip designs. Research preview live now.",
    image: "/images/news/meet-dsynq.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_dsynq-quantumx-activity-7482326198463664128-8mO9",
    country: null,
    kind: "Launch",
  },
  {
    date: "2026-07-10",
    displayDate: "Jul 10, 2026",
    title: "A great conversation on the future of security",
    summary: "Our founder spoke on internet crime, safety, and cyber security practice.",
    image: "/images/news/toc-h-knowledge-enhancement-programme.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_a-great-conversation-on-the-future-of-security-activity-7481266190137581568-JM5U",
    country: "in",
    kind: "Community",
  },
  {
    date: "2026-06-29",
    displayDate: "Jun 29, 2026",
    title: "Introducing Quark, our open-source quantum circuit fingerprinting tool",
    summary: "A lightweight model that finds duplicate quantum circuits fast, open-source and licensed.",
    image: "/images/news/meet-quark.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_new-product-quarks-activity-7476200202819883008-yT9a",
    country: null,
    kind: "Launch",
  },
  {
    date: "2026-06-22",
    displayDate: "Jun 22, 2026",
    title: "Here's the full curriculum for our Quantum Course",
    summary: "8 live sessions on quantum computing, Qiskit programming, and real-world applications.",
    image: "/images/news/quantum-course-curriculum.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_for-those-of-you-asking-for-the-course-curriculum-activity-7473320554876260352-IFzg",
    country: null,
    kind: "Launch",
  },
  {
    date: "2026-06-05",
    displayDate: "Jun 5, 2026",
    title: "Meet the winning teams of QX Hack",
    summary: "Infinity Loop, Nexus, and Anurag won top three spots at QX Hack.",
    image: "/images/news/qx-hack-winners.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_qx-hack-winners-activity-7464660424244776962-fZgB",
    country: "in",
    kind: "Community",
  },
  {
    date: "2026-05-15",
    displayDate: "May 15, 2026",
    title: "Spent the week in London",
    summary: "We visited Imperial College London and Oxford for research and innovation events.",
    image: "/images/news/london-imperial-oxford.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_spent-the-week-in-london-we-were-at-imperial-activity-7454411785757138944-eFMj",
    country: "gb",
    kind: "On the road",
  },
  {
    date: "2026-05-14",
    displayDate: "May 14, 2026",
    title: "Attended the BQIT:27 workshop at the University of Bristol",
    summary: "We discussed quantum information technology's future at the University of Bristol.",
    image: "/images/news/bqit27-bristol.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_attended-the-bqit27-workshop-at-the-university-activity-7455565891502514176-cDDj",
    country: "gb",
    kind: "On the road",
  },
  {
    date: "2026-05-13",
    displayDate: "May 13, 2026",
    title: "Announcing the Quantum for Social Good Hackathon",
    summary: "10 hours, real-world problems, and working MVPs built with quantum-inspired ideas.",
    image: "/images/news/quantum-for-social-good-hackathon.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_quantum-for-social-good-hackathon-most-activity-7457426757399486464-ILqY",
    country: "in",
    kind: "Community",
  },
  {
    date: "2026-05-12",
    displayDate: "May 12, 2026",
    title: "25+ curious minds, one quantum workshop with SkillUniv",
    summary: "We ran a quantum workshop and cohort session with SkillUniv.",
    image: "/images/news/skill-university-workshop.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_25-curious-minds-came-together-under-one-activity-7450524446429425664-3ghX",
    country: "in",
    kind: "Community",
  },
  {
    date: "2026-03-13",
    displayDate: "Mar 13, 2026",
    title: "The Quantum Future Series: Bengaluru community meetup",
    summary: "An evening of quantum conversations with developers, researchers, and the curious.",
    image: "/images/news/bengaluru-community-meetup.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_were-hosting-a-quantumx-community-meetup-activity-7432365496190287872-6IfS",
    country: "in",
    kind: "Community",
  },
  {
    date: "2026-03-10",
    displayDate: "Mar 10, 2026",
    title: "QuantumX School's first cohort is done",
    summary: "Our first QuantumX School cohort wrapped up, with more coming in March.",
    image: "/images/news/quantumx-school-first-cohort.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_quantumx-school-first-cohort-done-if-you-activity-7433501851091902464-RPUS",
    country: "in",
    kind: "Launch",
  },
  {
    date: "2026-03-01",
    displayDate: "Mar 1, 2026",
    title: "Two days that built momentum for quantum in Bengaluru",
    summary: "A workshop with SkillUniv, followed by a community meetup and panel.",
    image: "/images/news/quantumx-innovation-workshop.webp",
    url: "https://www.linkedin.com/posts/shreyansu-panda_quantumcomputing-quantumtechnology-quantumx-ugcPost-7434276285054582784-hCLS",
    country: "in",
    kind: "Community",
  },
  {
    date: "2026-02-23",
    displayDate: "Feb 23, 2026",
    title: "Speaking at Manipal Institute of Technology's 5-day Faculty Development Programme",
    summary: "A week on decoherence and post-quantum cryptography with faculty at MIT Bengaluru.",
    image: "/images/news/manipal-decoherence-talk.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_wrapped-up-a-brilliant-session-at-the-manipal-activity-7432765434355040256-e-0W",
    country: "in",
    kind: "Community",
  },
  {
    date: "2026-02-13",
    displayDate: "Feb 13, 2026",
    title: "Introducing the Qubit Database",
    summary: "A dashboard comparing qubit technologies built by companies and research labs worldwide.",
    image: "/images/news/qubit-database.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_qubit-dashboard-activity-7425123738037366784-tGM8",
    country: null,
    kind: "Launch",
  },
  {
    date: "2026-01-13",
    displayDate: "Jan 13, 2026",
    title: "Introducing the QuantumX Vulnerability Dashboard",
    summary: "A community dashboard tracking which security systems quantum computers could break.",
    image: "/images/news/vulnerability-dashboard.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_weve-been-working-on-something-and-were-activity-7416433882452893696-qHo-",
    country: null,
    kind: "Launch",
  },
  {
    date: "2025-12-13",
    displayDate: "Dec 13, 2025",
    title: "An inspiring session at NYU Abu Dhabi with Prof. John Martinis",
    summary: "We attended a seminar with Nobel laureate Prof. John Martinis on qubits.",
    image: "/images/news/nyu-abu-dhabi-john-martinis.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_wrapped-another-inspiring-session-at-nyu-activity-7400156123120504832-7nHO",
    country: "ae",
    kind: "On the road",
  },
  {
    date: "2025-12-10",
    displayDate: "Dec 10, 2025",
    title: "The quantum track at DeepTech Conf",
    summary: "Three talks on India's quantum readiness, security, communication, and post-quantum cryptography.",
    image: "/images/news/deeptech-conf-quantum-track.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_the-quantum-track-at-deeptech-conf-brought-activity-7401568443994697728-jjnd",
    country: "in",
    kind: "Community",
  },
  {
    date: "2025-11-26",
    displayDate: "Nov 26, 2025",
    title: "Attending CyberQ 2025 in Abu Dhabi",
    summary: "We joined CyberQ 2025 to explore the future of post-quantum cybersecurity.",
    image: "/images/news/cyberq-2025-abu-dhabi.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_excited-to-share-that-well-be-attending-activity-7397946275779928064-lHBJ",
    country: "ae",
    kind: "On the road",
  },
  {
    date: "2025-11-13",
    displayDate: "Nov 13, 2025",
    title: "A week in Kuala Lumpur at the Post-Quantum Cryptography Conference 2025",
    summary: "We joined the global community migrating to quantum-safe cryptography in Kuala Lumpur.",
    image: "/images/news/pqc-conference-kuala-lumpur.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_were-spending-the-week-in-kuala-lumpur-activity-7389540618332667907-2GW8",
    country: "my",
    kind: "On the road",
  },
  {
    date: "2025-11-12",
    displayDate: "Nov 12, 2025",
    title: "Bringing the quantum perspective to DeepTech Hackers Day",
    summary: "We joined a full-day jam on AI, Web3, and Quantum in Bengaluru.",
    image: "/images/news/deeptech-hackers-day.webp",
    url: "https://www.linkedin.com/posts/quantumx-foundation_startupfestival-activity-7389309557778518016-3eOg",
    country: "in",
    kind: "Community",
  },
];
