"""Turn Natural Earth land shapes into the pixel world map's land mask.

Usage: python3 scripts/world-map.py
Downloads world-atlas land-50m, rasterises it onto an equirectangular grid and
writes src/content/world.ts. Rerun only if the grid size below changes.
"""

import json
import urllib.request
from pathlib import Path

from PIL import Image, ImageDraw

URL = "https://cdn.jsdelivr.net/npm/world-atlas@2/land-50m.json"
OUT = Path("src/content/world.ts")

# Each cell is STEP degrees square. Antarctica is cropped off below LAT_MIN.
STEP = 2.5
LAT_MAX, LAT_MIN = 80.0, -57.5
COLS = int(360 / STEP)
ROWS = int((LAT_MAX - LAT_MIN) / STEP)
SUB = 8  # supersampling per cell
THRESHOLD = 0.3  # share of a cell that has to be land


def decode(topo):
    sx, sy = topo["transform"]["scale"]
    tx, ty = topo["transform"]["translate"]
    arcs = []
    for arc in topo["arcs"]:
        x = y = 0
        points = []
        for dx, dy in arc:
            x += dx
            y += dy
            points.append((x * sx + tx, y * sy + ty))
        arcs.append(points)
    return arcs


def ring(arcs, indexes):
    points = []
    for i in indexes:
        arc = arcs[i] if i >= 0 else arcs[~i][::-1]
        points.extend(arc[1:] if points else arc)
    return points


def main():
    topo = json.load(urllib.request.urlopen(URL))
    arcs = decode(topo)
    w, h = COLS * SUB, ROWS * SUB
    img = Image.new("L", (w, h), 0)
    draw = ImageDraw.Draw(img)

    def px(lon, lat):
        return ((lon + 180) / 360 * w, (LAT_MAX - lat) / (LAT_MAX - LAT_MIN) * h)

    for geometry in topo["objects"]["land"]["geometries"]:
        polygons = geometry["arcs"] if geometry["type"] == "MultiPolygon" else [geometry["arcs"]]
        for polygon in polygons:
            for n, indexes in enumerate(polygon):
                points = [px(lon, lat) for lon, lat in ring(arcs, indexes)]
                if len(points) > 2:
                    draw.polygon(points, fill=0 if n else 255)

    small = img.resize((COLS, ROWS), Image.Resampling.BOX)
    rows = [
        "".join("#" if small.getpixel((x, y)) / 255 >= THRESHOLD else "." for x in range(COLS))
        for y in range(ROWS)
    ]

    body = "\n".join(f'  "{row}",' for row in rows)
    OUT.write_text(
        f"""/**
 * Land mask for the pixel world map, generated by scripts/world-map.py from
 * Natural Earth (public domain). "#" is land. Equirectangular: each cell is
 * {STEP} degrees, longitude -180 to 180, latitude {LAT_MAX:g} to {LAT_MIN:g}.
 */
export const WORLD = {{ step: {STEP}, latMax: {LAT_MAX:g}, cols: {COLS}, rows: {ROWS} }};

export const LAND = [
{body}
];
"""
    )
    print(f"wrote {OUT} ({COLS}x{ROWS})")


main()
